### ISSUE TITLE
exp st crash on empty resultset (?)

### ISSUE THREAD

**Issue by rybafish** [rybafish/rybafish#559]
2022-01-13 17:47:02 [SQL]: select entity, "START", "STOP", details, title, memory_size from (select 
    host,
    port,
    start_time "START",
    add_seconds(start_time, duration_microsec/1000000) "STOP",
    db_user || '/' || app_user entity,
    to_int(memory_size/1024/1024) || ' MB' title,
    memory_size,
    'Duration: $duration, ' || to_varchar(to_integer(memory_size/1024/1024)) || ' MB, ' || operation || ': '
    || to_varchar(start_time, 'HH24:MI:SS.FF3') || ' - ' || to_varchar(add_seconds(start_time, duration_microsec/1000000), 'HH24:MI:SS.FF3') || '\n'
    || REPLACE_REGEXPR('[\n|\r]' in substr(statement_string, 0, 128) with '  ' OCCURRENCE ALL) details
    from m_expensive_statements
order by start_time desc
) where host = ? and port = ? and  "STOP" >= ? and "START" <= ? order by entity desc, "START"
2022-01-13 17:47:02 [E] unexpected DB error: time data '' does not match format '%Y-%m-%d %H:%M:%S'
2022-01-13 17:47:02 [!] execute_query: ("time data '' does not match format '%Y-%m-%d %H:%M:%S'", None)
>>Traceback (most recent call last):
  File "db.py", line 348, in execute_query_desc
  File "dbCursor.py", line 45, in execute_prepared
  File "pyhdb\connection.py", line 85, in send_request
  File "pyhdb\protocol\message.py", line 55, in pack
  File "pyhdb\protocol\message.py", line 45, in build_payload
  File "pyhdb\protocol\segments.py", line 94, in pack
  File "pyhdb\protocol\segments.py", line 80, in build_payload
  File "pyhdb\protocol\parts.py", line 103, in pack
  File "pyhdb\protocol\parts.py", line 506, in pack_data
  File "pyhdb\protocol\types.py", line 544, in prepare
  File "_strptime.py", line 568, in _strptime_datetime
  File "_strptime.py", line 349, in _strptime
ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dpDB.py", line 556, in getGanttData
  File "db.py", line 409, in execute_query_desc
utils.dbException: ("time data '' does not match format '%Y-%m-%d %H:%M:%S'", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dpDB.py", line 458, in getData
  File "dpDB.py", line 560, in getGanttData
utils.dbException: ('[db]: ("time data \'\' does not match format \'%Y-%m-%d %H:%M:%S\'", None)', None)

2022-01-13 17:47:02 yesNoDialog ---> disable 10_exp_st.yaml?

**Comment by rybafish** [comment]
have not seen it for a while...
